---
version: 1

kind: experiment

framework: pytorch

tags: [examples]
 
build:
  image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime
  build_steps:
    - pip install -r requirements.txt

environment:
  resources:
    cpu:
      requests: 3
      limits: 8
    memory:
      requests: 1024
      limits: 4098
    gpu:
      requests: 1
      limits: 1

declarations:
  batch_size_train: 4
  batch_size_test: 4
  epochs: 5
  lr: 0.001
  momentum: 0.9
  log_interval: 100

run:
  cmd: python -u run_diff_nets_group.py

